# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kurt_spec_frame.ui'
#
# Created: Fri Aug  9 19:05:13 2013
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets, QtGui

class Ui_kurtosisMC(object):
    def setupUi(self, kurtosisMC):
        kurtosisMC.setObjectName("kurtosisMC")
        kurtosisMC.resize(633, 591)
        kurtosisMC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        kurtosisMC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayoutWidget = QtWidgets.QWidget(kurtosisMC)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 500, 151, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.accumLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.accumLayout.setObjectName("accumLayout")
        self.accumLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.accumLabel.setFont(font)
        self.accumLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.accumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.accumLabel.setObjectName("accumLabel")
        self.accumLayout.addWidget(self.accumLabel)
        self.accumSpin = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.accumSpin.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.accumSpin.setMinimum(1)
        self.accumSpin.setMaximum(63)
        self.accumSpin.setProperty("value", 63)
        self.accumSpin.setObjectName("accumSpin")
        self.accumLayout.addWidget(self.accumSpin)
        self.ADCsnapGroup = QtWidgets.QGroupBox(kurtosisMC)
        self.ADCsnapGroup.setGeometry(QtCore.QRect(10, 0, 151, 121))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.ADCsnapGroup.setFont(font)
        self.ADCsnapGroup.setCheckable(False)
        self.ADCsnapGroup.setObjectName("ADCsnapGroup")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.ADCsnapGroup)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 111, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.polSelectLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.polSelectLayout.setObjectName("polSelectLayout")
        self.pol0select = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.pol0select.setChecked(True)
        self.pol0select.setObjectName("pol0select")
        self.polSelectLayout.addWidget(self.pol0select)
        self.pol1select = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.pol1select.setObjectName("pol1select")
        self.polSelectLayout.addWidget(self.pol1select)
        self.polsselect = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.polsselect.setObjectName("polsselect")
        self.polSelectLayout.addWidget(self.polsselect)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(kurtosisMC)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 120, 151, 101))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.syncSelBoxLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.syncSelBoxLayout.setObjectName("syncSelBoxLayout")
        self.syncSelGroup = QtWidgets.QGroupBox(self.verticalLayoutWidget_5)
        self.syncSelGroup.setObjectName("syncSelGroup")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.syncSelGroup)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 81, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.syncSelLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.syncSelLayout.setObjectName("syncSelLayout")
        self.syncSel1pps = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.syncSel1pps.setChecked(True)
        self.syncSel1pps.setObjectName("syncSel1pps")
        self.syncSelLayout.addWidget(self.syncSel1pps)
        self.syncSelRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.syncSelRadio.setObjectName("syncSelRadio")
        self.syncSelLayout.addWidget(self.syncSelRadio)
        self.syncSelBoxLayout.addWidget(self.syncSelGroup)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(kurtosisMC)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 250, 151, 131))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.currentSecLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.currentSecLayout.setObjectName("currentSecLayout")
        self.currentSec = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                                        QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentSec.sizePolicy().hasHeightForWidth())
        self.currentSec.setSizePolicy(sizePolicy)
        self.currentSec.setAlignment(QtCore.Qt.AlignCenter)
        self.currentSec.setWordWrap(True)
        self.currentSec.setObjectName("currentSec")
        self.currentSecLayout.addWidget(self.currentSec)
        self.pktCntRstSelectgroup = QtWidgets.QGroupBox(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                                      QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
                     self.pktCntRstSelectgroup.sizePolicy().hasHeightForWidth())
        self.pktCntRstSelectgroup.setSizePolicy(sizePolicy)
        self.pktCntRstSelectgroup.setObjectName("pktCntRstSelectgroup")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.pktCntRstSelectgroup)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 111, 51))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.pktCntRstSelLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.pktCntRstSelLayout.setObjectName("pktCntRstSelLayout")
        self.pktCntRstSyncradio = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
                       self.pktCntRstSyncradio.sizePolicy().hasHeightForWidth())
        self.pktCntRstSyncradio.setSizePolicy(sizePolicy)
        self.pktCntRstSyncradio.setChecked(True)
        self.pktCntRstSyncradio.setObjectName("pktCntRstSyncradio")
        self.pktCntRstSelLayout.addWidget(self.pktCntRstSyncradio)
        self.pktCntRst1ppsradio = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
                       self.pktCntRst1ppsradio.sizePolicy().hasHeightForWidth())
        self.pktCntRst1ppsradio.setSizePolicy(sizePolicy)
        self.pktCntRst1ppsradio.setObjectName("pktCntRst1ppsradio")
        self.pktCntRstSelLayout.addWidget(self.pktCntRst1ppsradio)
        self.currentSecLayout.addWidget(self.pktCntRstSelectgroup)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(kurtosisMC)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(160, 0, 149, 301))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.rawCountLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.rawCountLayout.setSpacing(1)
        self.rawCountLayout.setObjectName("rawCountLayout")
        self.totalCountLayout = QtWidgets.QVBoxLayout()
        self.totalCountLayout.setSpacing(1)
        self.totalCountLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.totalCountLayout.setObjectName("totalCountLayout")
        self.pktCntValue = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.pktCntValue.setMaxLength(10)
        self.pktCntValue.setEchoMode(QtWidgets.QLineEdit.NoEcho)
        self.pktCntValue.setReadOnly(True)
        self.pktCntValue.setObjectName("pktCntValue")
        self.totalCountLayout.addWidget(self.pktCntValue)
        self.pktCntLabel = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktCntLabel.sizePolicy().hasHeightForWidth())
        self.pktCntLabel.setSizePolicy(sizePolicy)
        self.pktCntLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pktCntLabel.setObjectName("pktCntLabel")
        self.totalCountLayout.addWidget(self.pktCntLabel)
        self.cntTypeGroup = QtWidgets.QGroupBox(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cntTypeGroup.sizePolicy().hasHeightForWidth())
        self.cntTypeGroup.setSizePolicy(sizePolicy)
        self.cntTypeGroup.setObjectName("cntTypeGroup")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.cntTypeGroup)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 30, 131, 51))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.rawCountTypeLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.rawCountTypeLayout.setObjectName("rawCountTypeLayout")
        self.countTypePktsRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countTypePktsRadio.sizePolicy().hasHeightForWidth())
        self.countTypePktsRadio.setSizePolicy(sizePolicy)
        self.countTypePktsRadio.setChecked(True)
        self.countTypePktsRadio.setObjectName("countTypePktsRadio")
        self.rawCountTypeLayout.addWidget(self.countTypePktsRadio)
        self.countTypeTicksRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countTypeTicksRadio.sizePolicy().hasHeightForWidth())
        self.countTypeTicksRadio.setSizePolicy(sizePolicy)
        self.countTypeTicksRadio.setObjectName("countTypeTicksRadio")
        self.rawCountTypeLayout.addWidget(self.countTypeTicksRadio)
        self.totalCountLayout.addWidget(self.cntTypeGroup)
        self.rawCountLayout.addLayout(self.totalCountLayout)
        self.rawCountResetGroup = QtWidgets.QGroupBox(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawCountResetGroup.sizePolicy().hasHeightForWidth())
        self.rawCountResetGroup.setSizePolicy(sizePolicy)
        self.rawCountResetGroup.setObjectName("rawCountResetGroup")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.rawCountResetGroup)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(20, 30, 81, 80))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.rawCountRstLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.rawCountRstLayout.setObjectName("rawCountRstLayout")
        self.rawRstSyncRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawRstSyncRadio.sizePolicy().hasHeightForWidth())
        self.rawRstSyncRadio.setSizePolicy(sizePolicy)
        self.rawRstSyncRadio.setChecked(True)
        self.rawRstSyncRadio.setObjectName("rawRstSyncRadio")
        self.rawCountRstLayout.addWidget(self.rawRstSyncRadio)
        self.rawRst1ppsRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawRst1ppsRadio.sizePolicy().hasHeightForWidth())
        self.rawRst1ppsRadio.setSizePolicy(sizePolicy)
        self.rawRst1ppsRadio.setObjectName("rawRst1ppsRadio")
        self.rawCountRstLayout.addWidget(self.rawRst1ppsRadio)
        self.rawRstUserRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawRstUserRadio.sizePolicy().hasHeightForWidth())
        self.rawRstUserRadio.setSizePolicy(sizePolicy)
        self.rawRstUserRadio.setObjectName("rawRstUserRadio")
        self.rawCountRstLayout.addWidget(self.rawRstUserRadio)
        self.rawCountLayout.addWidget(self.rawCountResetGroup)
        self.rawRstUserPush = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.rawRstUserPush.setObjectName("rawRstUserPush")
        self.rawCountLayout.addWidget(self.rawRstUserPush)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(kurtosisMC)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(160, 300, 151, 281))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.gbe0layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.gbe0layout.setObjectName("gbe0layout")
        self.gbe0label = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbe0label.sizePolicy().hasHeightForWidth())
        self.gbe0label.setSizePolicy(sizePolicy)
        self.gbe0label.setAlignment(QtCore.Qt.AlignCenter)
        self.gbe0label.setObjectName("gbe0label")
        self.gbe0layout.addWidget(self.gbe0label)
        self.gbe0linkCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget_11)
        self.gbe0linkCheck.setCheckable(False)
        self.gbe0linkCheck.setObjectName("gbe0linkCheck")
        self.gbe0layout.addWidget(self.gbe0linkCheck)
        self.gbe0xmitCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget_11)
        self.gbe0xmitCheck.setCheckable(False)
        self.gbe0xmitCheck.setObjectName("gbe0xmitCheck")
        self.gbe0layout.addWidget(self.gbe0xmitCheck)
        self.gbe0fullCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget_11)
        self.gbe0fullCheck.setObjectName("gbe0fullCheck")
        self.gbe0layout.addWidget(self.gbe0fullCheck)
        self.gbe0oflowCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget_11)
        self.gbe0oflowCheck.setObjectName("gbe0oflowCheck")
        self.gbe0layout.addWidget(self.gbe0oflowCheck)
        self.gbe0pktCntLabel = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbe0pktCntLabel.sizePolicy().hasHeightForWidth())
        self.gbe0pktCntLabel.setSizePolicy(sizePolicy)
        self.gbe0pktCntLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gbe0pktCntLabel.setObjectName("gbe0pktCntLabel")
        self.gbe0layout.addWidget(self.gbe0pktCntLabel)
        self.gbe0pktCntValue = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.gbe0pktCntValue.setMaxLength(10)
        self.gbe0pktCntValue.setObjectName("gbe0pktCntValue")
        self.gbe0layout.addWidget(self.gbe0pktCntValue)
        self.gbe0sourceGroup = QtWidgets.QGroupBox(self.verticalLayoutWidget_11)
        self.gbe0sourceGroup.setObjectName("gbe0sourceGroup")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.gbe0sourceGroup)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(10, 30, 121, 51))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.gbe0sourceLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.gbe0sourceLayout.setObjectName("gbe0sourceLayout")
        self.gbe0sourceDspRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget_12)
        self.gbe0sourceDspRadio.setChecked(True)
        self.gbe0sourceDspRadio.setObjectName("gbe0sourceDspRadio")
        self.gbe0sourceLayout.addWidget(self.gbe0sourceDspRadio)
        self.gbe0sourceTestRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget_12)
        self.gbe0sourceTestRadio.setObjectName("gbe0sourceTestRadio")
        self.gbe0sourceLayout.addWidget(self.gbe0sourceTestRadio)
        self.gbe0layout.addWidget(self.gbe0sourceGroup)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(kurtosisMC)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(10, 390, 152, 101))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.powerBitsSelectLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.powerBitsSelectLayout.setObjectName("powerBitsSelectLayout")
        self.powerBitsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerBitsLabel.sizePolicy().hasHeightForWidth())
        self.powerBitsLabel.setSizePolicy(sizePolicy)
        self.powerBitsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.powerBitsLabel.setWordWrap(True)
        self.powerBitsLabel.setObjectName("powerBitsLabel")
        self.powerBitsSelectLayout.addWidget(self.powerBitsLabel)
        self.powerBitsSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_13)
        self.powerBitsSpinBox.setMinimum(5)
        self.powerBitsSpinBox.setMaximum(31)
        self.powerBitsSpinBox.setObjectName("powerBitsSpinBox")
        self.powerBitsSelectLayout.addWidget(self.powerBitsSpinBox)
        self.powerBitsSlider = QtWidgets.QSlider(self.verticalLayoutWidget_13)
        self.powerBitsSlider.setMaximum(63)
        self.powerBitsSlider.setPageStep(16)
        self.powerBitsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.powerBitsSlider.setObjectName("powerBitsSlider")
        self.powerBitsSelectLayout.addWidget(self.powerBitsSlider)
        self.syncPush = QtWidgets.QPushButton(kurtosisMC)
        self.syncPush.setGeometry(QtCore.QRect(30, 220, 101, 28))
        self.syncPush.setObjectName("syncPush")

        self.retranslateUi(kurtosisMC)
        QtCore.QObject.connect(self.powerBitsSpinBox, QtCore.SIGNAL("valueChanged(int)"), self.powerBitsSlider.setValue)
        QtCore.QObject.connect(self.ADCsnapGroup, QtCore.SIGNAL("clicked()"), kurtosisMC.update)
        QtCore.QObject.connect(self.syncSelGroup, QtCore.SIGNAL("clicked()"), kurtosisMC.update)
        QtCore.QObject.connect(self.syncPush, QtCore.SIGNAL("pressed()"), kurtosisMC.update)
        QtCore.QObject.connect(self.pktCntRstSelectgroup, QtCore.SIGNAL("clicked()"), kurtosisMC.update)
        QtCore.QObject.connect(self.powerBitsSpinBox, QtCore.SIGNAL("valueChanged(int)"), kurtosisMC.update)
        QtCore.QObject.connect(self.gbe0linkCheck, QtCore.SIGNAL("stateChanged(int)"), kurtosisMC.update)
        QtCore.QObject.connect(self.gbe0xmitCheck, QtCore.SIGNAL("stateChanged(int)"), kurtosisMC.update)
        QtCore.QObject.connect(self.gbe0fullCheck, QtCore.SIGNAL("stateChanged(int)"), kurtosisMC.update)
        QtCore.QObject.connect(self.gbe0oflowCheck, QtCore.SIGNAL("stateChanged(int)"), kurtosisMC.update)
        QtCore.QObject.connect(self.gbe0sourceGroup, QtCore.SIGNAL("clicked()"), kurtosisMC.update)
        QtCore.QObject.connect(self.rawCountResetGroup, QtCore.SIGNAL("clicked()"), kurtosisMC.update)
        QtCore.QMetaObject.connectSlotsByName(kurtosisMC)

    def retranslateUi(self, kurtosisMC):
        kurtosisMC.setWindowTitle(QtWidgets.QApplication.translate("kurtosisMC", "Frame", None, QtWidgets.QApplication.UnicodeUTF8))
        self.accumLabel.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "Number of spectra per accumulation", None, QtWidgets.QApplication.UnicodeUTF8))
        self.accumLabel.setText(QtWidgets.QApplication.translate("kurtosisMC", "Spectra per intgn", None, QtWidgets.QApplication.UnicodeUTF8))
        self.accumSpin.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "63 spectra = 100 us", None, QtWidgets.QApplication.UnicodeUTF8))
        self.ADCsnapGroup.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "Selects trigger source for ADC BRAM snapshots", None, QtWidgets.QApplication.UnicodeUTF8))
        self.ADCsnapGroup.setTitle(QtWidgets.QApplication.translate("kurtosisMC", "ADC Snap Trigger", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pol0select.setText(QtWidgets.QApplication.translate("kurtosisMC", "Pol 0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pol1select.setText(QtWidgets.QApplication.translate("kurtosisMC", "Pol 1", None, QtWidgets.QApplication.UnicodeUTF8))
        self.polsselect.setText(QtWidgets.QApplication.translate("kurtosisMC", "Both pols", None, QtWidgets.QApplication.UnicodeUTF8))
        self.syncSelGroup.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "Source of DSP sync pulses", None, QtWidgets.QApplication.UnicodeUTF8))
        self.syncSelGroup.setTitle(QtWidgets.QApplication.translate("kurtosisMC", "Sync Select", None, QtWidgets.QApplication.UnicodeUTF8))
        self.syncSel1pps.setText(QtWidgets.QApplication.translate("kurtosisMC", "1 PPS", None, QtWidgets.QApplication.UnicodeUTF8))
        self.syncSelRadio.setText(QtWidgets.QApplication.translate("kurtosisMC", "User", None, QtWidgets.QApplication.UnicodeUTF8))
        self.currentSec.setWhatsThis(QtWidgets.QApplication.translate("kurtosisMC", "Assign a sequence number to the packet during each second", None, QtWidgets.QApplication.UnicodeUTF8))
        self.currentSec.setText(QtWidgets.QApplication.translate("kurtosisMC", "Current second packet number", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pktCntRstSelectgroup.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "Source of reset for current second packet counter", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pktCntRstSelectgroup.setTitle(QtWidgets.QApplication.translate("kurtosisMC", "reset select", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pktCntRstSyncradio.setText(QtWidgets.QApplication.translate("kurtosisMC", "sync", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pktCntRst1ppsradio.setText(QtWidgets.QApplication.translate("kurtosisMC", "1 PPS", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pktCntValue.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "Counts packets or FPGA clock ticks since last reset", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pktCntLabel.setText(QtWidgets.QApplication.translate("kurtosisMC", "Total count", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cntTypeGroup.setTitle(QtWidgets.QApplication.translate("kurtosisMC", "Counter units", None, QtWidgets.QApplication.UnicodeUTF8))
        self.countTypePktsRadio.setText(QtWidgets.QApplication.translate("kurtosisMC", "packets", None, QtWidgets.QApplication.UnicodeUTF8))
        self.countTypeTicksRadio.setText(QtWidgets.QApplication.translate("kurtosisMC", "system ticks", None, QtWidgets.QApplication.UnicodeUTF8))
        self.rawCountResetGroup.setTitle(QtWidgets.QApplication.translate("kurtosisMC", "Reset select", None, QtWidgets.QApplication.UnicodeUTF8))
        self.rawRstSyncRadio.setText(QtWidgets.QApplication.translate("kurtosisMC", "sync", None, QtWidgets.QApplication.UnicodeUTF8))
        self.rawRst1ppsRadio.setText(QtWidgets.QApplication.translate("kurtosisMC", "1 PPS", None, QtWidgets.QApplication.UnicodeUTF8))
        self.rawRstUserRadio.setText(QtWidgets.QApplication.translate("kurtosisMC", "User", None, QtWidgets.QApplication.UnicodeUTF8))
        self.rawRstUserPush.setText(QtWidgets.QApplication.translate("kurtosisMC", "Reset", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0label.setText(QtWidgets.QApplication.translate("kurtosisMC", "10 GbE 0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0linkCheck.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "10 GbE port 0 has a connection", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0linkCheck.setText(QtWidgets.QApplication.translate("kurtosisMC", "linked up", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0xmitCheck.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "10 GbE port 0 is sending data", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0xmitCheck.setText(QtWidgets.QApplication.translate("kurtosisMC", "transmitting", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0fullCheck.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "10 GbE 0 buffer is almost full", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0fullCheck.setText(QtWidgets.QApplication.translate("kurtosisMC", "full", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0oflowCheck.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "10 GbE 0 buffer has overflowed; data lost", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0oflowCheck.setText(QtWidgets.QApplication.translate("kurtosisMC", "overflowed", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0pktCntLabel.setText(QtWidgets.QApplication.translate("kurtosisMC", "Packet count", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0sourceGroup.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "Optional test data for debugging 10 GbE", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0sourceGroup.setTitle(QtWidgets.QApplication.translate("kurtosisMC", "Data source", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0sourceDspRadio.setText(QtWidgets.QApplication.translate("kurtosisMC", "DSP output", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gbe0sourceTestRadio.setText(QtWidgets.QApplication.translate("kurtosisMC", "Test data", None, QtWidgets.QApplication.UnicodeUTF8))
        self.powerBitsLabel.setText(QtWidgets.QApplication.translate("kurtosisMC", "Power bit select for 10GbE", None, QtWidgets.QApplication.UnicodeUTF8))
        self.powerBitsSpinBox.setToolTip(QtWidgets.QApplication.translate("kurtosisMC", "Offset from MSB for the 16 bits of power accumulator to send to 10 GbE", None, QtWidgets.QApplication.UnicodeUTF8))
        self.syncPush.setText(QtWidgets.QApplication.translate("kurtosisMC", "Sync pulse", None, QtWidgets.QApplication.UnicodeUTF8))

